import React from 'react';

const Terminos = () => {
    return (
        <div style={{margin: '10% 0 0 0'}}>
        <h1>Terms of Service</h1>
        <p>Updated at 2020-09-01</p>

        <h1>License</h1>
        <p>
        Jornadas Magallánicas grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the app strictly in accordance with the terms of this Agreement.</p>

        <h1>Meanings</h1>
        <p>For this Privacy Policy:
        <ul>
        <li>You is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to , </li>
        <li>Website is referred to Jornadas Magallánicas, accessible from </li>
        <li>Service is referred to the app.</li>
        <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li>Third-party Social Media Service could be any website or social network website in which a User can log in or create an account to use the Service.</li>
        <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
        <li>Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.</li>
        <li>Device could be any device with internet who can access the service such as a mobile phone, a computer or a digital tablet.</li>
        <li>Usage Data it’s referred to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the app.</li>
        </ul>
        </p>

        <h1>Restrictions</h1>
        <p>You agree not to, and you will not permit others to:</p>
        <ul>
        <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the app or make the platform available to any third party.</li>
        <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the app.</li>
        <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Jornadas Magallánicas or its affiliates, partners, suppliers or the licensors of the app.</li>
        </ul>
        <h1>Return and Refund Policy</h1>
        <p>If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p>

        <h1>Your Suggestions</h1>
        <p>Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Jornadas Magallánicas with respect to the app shall remain the sole and exclusive property of Jornadas Magallánicas.</p>
        <p>Jornadas Magallánicas shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.</p>

        <h1>Your Consent</h1>
        <p>By using our site, registering an account, or making a purchase, you consent to this Terms of Service.</p>

        <h1>Links to Other Websites</h1>
        <p>Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Terms of Service of every site You visit.</p>
        <p>We have no control over and assume no responsibility for the content, Terms of Service or practices of any third party sites or services.</p>

        <h1>Cookies</h1>
        <p>Jornadas Magallánicas uses "Cookies" to identify the areas of our app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our app. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our app correctly or at all. We never place Personally Identifiable Information in Cookies. By using our site, registering an account, or making a purchase, you consent to the fact that we use cookies.</p>

        <h1>Changes To Our Terms of Service</h1>
        <p>You acknowledge and agree that Jornadas Magallánicas may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Jornadas Magallánicas’s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Jornadas Magallánicas when you stop using the Service. You acknowledge and agree that if  Jornadas Magallánicas disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.</p>
        <p>If we decide to change our Terms of Service, we will post those changes on this page, and/or update the Terms of Service modification date below.</p>

        <h1>Modifications to Our app</h1>
        <p>Jornadas Magallánicas reserves the right to modify, suspend or discontinue, temporarily or permanently, the app
        or any service to which it connects, with or without notice and without liability to you.</p>

        <h1>Updates to Our app</h1>
        <p>Jornadas Magallánicas may from time to time provide enhancements or improvements to the features/ functionality of the app, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").</p>
        <p>Updates may modify or delete certain features and/or functionalities of the app. You agree that Jornadas Magallánicas has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the app to you.</p>
        <p>You further agree that all Updates will be (i) deemed to constitute an integral part of the app, and (ii) subject to the terms and conditions of this Agreement.</p>

        <h1>Third-Party Services</h1>
        <p>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</p>
        <p>You acknowledge and agree that Jornadas Magallánicas shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Jornadas Magallánicas does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</p>
        <p>Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</p>

        <h1>Term and Termination</h1>
        <p>This Agreement shall remain in effect until terminated by you or Jornadas Magallánicas.</p>
        <p>Jornadas Magallánicas may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</p>
        <p>This Agreement will terminate immediately, without prior notice from Jornadas Magallánicas, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the app and all copies thereof from your computer.</p>
        <p>Upon termination of this Agreement, you shall cease all use of the app and delete all copies of the app from your computer.</p>
        <p>Termination of this Agreement will not limit any of Jornadas Magallánicas's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</p>

        <h1>Indemnification</h1>
        <p>You agree to indemnify and hold Jornadas Magallánicas and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>

        <h1>No Warranties</h1>
        <p>The app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Jornadas Magallánicas, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the app, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Jornadas Magallánicas provides no warranty or undertaking, and makes no representation of any kind that the app will meet your requirements, achieve any intended results, be compatible or work with any other software, , systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
        <p>Without limiting the foregoing, neither Jornadas Magallánicas nor any Jornadas Magallánicas's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the app, or the information, content, and materials or products included thereon; (ii) that the app will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the app; or (iv) that the app, its servers, the content, or e-mails sent from or on behalf of Jornadas Magallánicas are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
        <p>Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</p>

        <h1>Limitation of Liability</h1>
        <p>Notwithstanding any damages that you might incur, the entire liability of Jornadas Magallánicas and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the app.</p>
        <p>To the maximum extent permitted by applicable law, in no event shall Jornadas Magallánicas or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the app, third-party software and/or third-party hardware used with the app, or otherwise in connection with any provision of this Agreement), even if Jornadas Magallánicas or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
        <p>Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</p>

        <h1>Severability</h1>
        <p>If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>

        <h1>Waiver</h1>
        <p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.</p>

        <h1>Amendments to this Agreement</h1>
        <p>Jornadas Magallánicas reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
        <p>By continuing to access or use our app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Jornadas Magallánicas.</p>

        <h1>Entire Agreement</h1>
        <p>The Agreement constitutes the entire agreement between you and Jornadas Magallánicas regarding your use of the app and supersedes all prior and contemporaneous written or oral agreements between you and Jornadas Magallánicas.</p>
        <p>You may be subject to additional terms and conditions that apply when you use or purchase other Jornadas Magallánicas's  services, which Jornadas Magallánicas will provide to you at the time of such use or purchase.</p>

        <h1>Disclaimer</h1>
        <p>Jornadas Magallánicas is not responsible for any content, code or any other imprecision.</p>
        <p>Jornadas Magallánicas does not provide warranties or guarantees.</p>
        <p>In no event shall Jornadas Magallánicas be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>

        <h1>Contact Us</h1>
        <p>Don't hesitate to contact us if you have any questions.</p>
        <ul><li>Via Email: contacto@appjornadasmagallanicas.cl></li><li>Via this Link:  https://www.appjornadasmagallanicas.cl</li>
        </ul>
        </div>
    );
}
 
export default Terminos;